@{
    @"pattern": @"move",
    @"replacement": @"moves",
    @"type": @"irregular"
},
@{
    @"pattern": @"sex",
    @"replacement": @"sexes",
    @"type": @"irregular"
},
@{
    @"pattern": @"child",
    @"replacement": @"children",
    @"type": @"irregular"
},
@{
    @"pattern": @"man",
    @"replacement": @"men",
    @"type": @"irregular"
},
@{
    @"pattern": @"person",
    @"replacement": @"people",
    @"type": @"irregular"
}
