@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(quiz)$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1zes"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"^(ox)$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1en"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"([m|l])ouse$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1ice"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(matr|vert|ind)ix|ex$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1ices"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(x|ch|ss|sh)$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1es"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"([^aeiouy]|qu)y$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1ies"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(hive)$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1s"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(?:([^f])fe|([lr])f)$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1$2ves"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"sis$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"ses"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"([ti])um$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1a"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(buffal|tomat)o$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1oes"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(bu)s$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1ses"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(alias|status)$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1es"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(octop|vir)us$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1i"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(ax|test)is$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1es"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"([a-z]+)s$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1s"
},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"([a-z]+)$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1s"
}
