@{
    @"pattern": @"(quiz)$",
    @"replacement": @"$1zes"
},
@{
    @"pattern": @"^(ox)$",
    @"replacement": @"$1en"
},
@{
    @"pattern": @"([m|l])ouse$",
    @"replacement": @"$1ice"
},
@{
    @"pattern": @"(matr|vert|ind)ix|ex$",
    @"replacement": @"$1ices"
},
@{
    @"pattern": @"(x|ch|ss|sh)$",
    @"replacement": @"$1es"
},
@{
    @"pattern": @"([^aeiouy]|qu)y$",
    @"replacement": @"$1ies"
},
@{
    @"pattern": @"(hive)$",
    @"replacement": @"$1s"
},
@{
    @"pattern": @"(?:([^f])fe|([lr])f)$",
    @"replacement": @"$1$2ves"
},
@{
    @"pattern": @"sis$",
    @"replacement": @"ses"
},
@{
    @"pattern": @"([ti])um$",
    @"replacement": @"$1a"
},
@{
    @"pattern": @"(buffal|tomat)o$",
    @"replacement": @"$1oes"
},
@{
    @"pattern": @"(bu)s$",
    @"replacement": @"$1ses"
},
@{
    @"pattern": @"(alias|status)$",
    @"replacement": @"$1es"
},
@{
    @"pattern": @"(octop|vir)us$",
    @"replacement": @"$1i"
},
@{
    @"pattern": @"(ax|test)is$",
    @"replacement": @"$1es"
},
@{
    @"pattern": @"([a-z]+)s$",
    @"replacement": @"$1s"
},
@{
    @"pattern": @"([a-z]+)$",
    @"replacement": @"$1s"
}
