@{
    @"pattern": @"(quiz)$",
    @"replacement": @"$1zes",
    @"type": @"plural"
},
@{
    @"pattern": @"^(ox)$",
    @"replacement": @"$1en",
    @"type": @"plural"
},
@{
    @"pattern": @"([m|l])ouse$",
    @"replacement": @"$1ice",
    @"type": @"plural"
},
@{
    @"pattern": @"(matr|vert|ind)ix|ex$",
    @"replacement": @"$1ices",
    @"type": @"plural"
},
@{
    @"pattern": @"(x|ch|ss|sh)$",
    @"replacement": @"$1es",
    @"type": @"plural"
},
@{
    @"pattern": @"([^aeiouy]|qu)y$",
    @"replacement": @"$1ies",
    @"type": @"plural"
},
@{
    @"pattern": @"(hive)$",
    @"replacement": @"$1s",
    @"type": @"plural"
},
@{
    @"pattern": @"(?:([^f])fe|([lr])f)$",
    @"replacement": @"$1$2ves",
    @"type": @"plural"
},
@{
    @"pattern": @"sis$",
    @"replacement": @"ses",
    @"type": @"plural"
},
@{
    @"pattern": @"([ti])um$",
    @"replacement": @"$1a",
    @"type": @"plural"
},
@{
    @"pattern": @"(buffal|tomat)o$",
    @"replacement": @"$1oes",
    @"type": @"plural"
},
@{
    @"pattern": @"(bu)s$",
    @"replacement": @"$1ses",
    @"type": @"plural"
},
@{
    @"pattern": @"(alias|status)$",
    @"replacement": @"$1es",
    @"type": @"plural"
},
@{
    @"pattern": @"(octop|vir)us$",
    @"replacement": @"$1i",
    @"type": @"plural"
},
@{
    @"pattern": @"(ax|test)is$",
    @"replacement": @"$1es",
    @"type": @"plural"
},
@{
    @"pattern": @"([a-z]+)s$",
    @"replacement": @"$1s",
    @"type": @"plural"
},
@{
    @"pattern": @"([a-z]+)$",
    @"replacement": @"$1s",
    @"type":
    @"plural"
}
