@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(quiz)zes$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(matr)ices$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1ix"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(vert|ind)ices$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1ex"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"^(ox)en" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(alias|status)es$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(octop|vir)i$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1us"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(cris|ax|test)es$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1is"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(shoe)s$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(o)es$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(bus)es$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"([m|l])ice$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1ouse"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(x|ch|ss|sh)es$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(m)ovies$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1ovie"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(s)eries$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1eries"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"([^aeiouy]|qu)ies$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1y"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"([lr])ves$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1f"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(tive)s$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(hive)s$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"([^f])ves$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1fe"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(^analy)ses$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1sis"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1\2sis"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"([ti])a$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1um"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"(n)ews$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @"$1ews"},
@{
    @"regex": [NSRegularExpression regularExpressionWithPattern:@"s$" options:NSRegularExpressionCaseInsensitive error:NULL],
    @"replacement": @""
}
