@{
    @"pattern": @"(quiz)zes$",
    @"replacement": @"$1",
    @"type": @"singular"
},
@{
    @"pattern": @"(matr)ices$",
    @"replacement": @"$1ix",
    @"type": @"singular"
},
@{
    @"pattern": @"(vert|ind)ices$",
    @"replacement": @"$1ex",
    @"type": @"singular"
},
@{
    @"pattern": @"^(ox)en",
    @"replacement": @"$1",
    @"type": @"singular"
},
@{
    @"pattern": @"(alias|status)es$",
    @"replacement": @"$1",
    @"type": @"singular"
},
@{
    @"pattern": @"(octop|vir)i$",
    @"replacement": @"$1us",
    @"type": @"singular"
},
@{
    @"pattern": @"(cris|ax|test)es$",
    @"replacement": @"$1is",
    @"type": @"singular"
},
@{
    @"pattern": @"(shoe)s$",
    @"replacement": @"$1",
    @"type": @"singular"
},
@{
    @"pattern": @"(o)es$",
    @"replacement": @"$1",
    @"type": @"singular"
},
@{
    @"pattern": @"(bus)es$",
    @"replacement": @"$1",
    @"type": @"singular"
},
@{
    @"pattern": @"([m|l])ice$",
    @"replacement": @"$1ouse",
    @"type": @"singular"
},
@{
    @"pattern": @"(x|ch|ss|sh)es$",
    @"replacement": @"$1",
    @"type": @"singular"
},
@{
    @"pattern": @"(m)ovies$",
    @"replacement": @"$1ovie",
    @"type": @"singular"
},
@{
    @"pattern": @"(s)eries$",
    @"replacement": @"$1eries",
    @"type": @"singular"
},
@{
    @"pattern": @"([^aeiouy]|qu)ies$",
    @"replacement": @"$1y",
    @"type": @"singular"
},
@{
    @"pattern": @"([lr])ves$",
    @"replacement": @"$1f",
    @"type": @"singular"
},
@{
    @"pattern": @"(tive)s$",
    @"replacement": @"$1",
    @"type": @"singular"
},
@{
    @"pattern": @"(hive)s$",
    @"replacement": @"$1",
    @"type": @"singular"
},
@{
    @"pattern": @"([^f])ves$",
    @"replacement": @"$1fe",
    @"type": @"singular"
},
@{
    @"pattern": @"(^analy)ses$",
    @"replacement": @"$1sis",
    @"type": @"singular"
},
@{
    @"pattern": @"((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$",
    @"replacement": @"$1\2sis",
    @"type": @"singular"
},
@{
    @"pattern": @"([ti])a$",
    @"replacement": @"$1um",
    @"type": @"singular"
},
@{
    @"pattern": @"(n)ews$",
    @"replacement": @"$1ews",
    @"type": @"singular"
},
@{
    @"pattern": @"s$",
    @"replacement": @"",
    @"type": @"singular"
}
