@{
    @"pattern": @"sheep",
    @"type": @"uncountable"
},
@{
    @"pattern": @"fish",
    @"type": @"uncountable"
},
@{
    @"pattern": @"series",
    @"type": @"uncountable"
},
@{
    @"pattern": @"species",
    @"type": @"uncountable"
},
@{
    @"pattern": @"money",
    @"type": @"uncountable"
},
@{
    @"pattern": @"rice",
    @"type": @"uncountable"
},
@{
    @"pattern": @"information",
    @"type": @"uncountable"
},
@{
    @"pattern": @"equipment",
    @"type": @"uncountable"
}
