BEGIN TRANSACTION;
DROP TABLE IF EXISTS foo;
CREATE TABLE foo ("uuid" TEXT PRIMARY KEY NOT NULL, "bar" TEXT DEFAULT NULL, "baz" TEXT DEFAULT NULL, "integer" INTEGER DEFAULT NULL);
INSERT INTO "foo" VALUES(1,'foobarbaz','bazbazb',1337);
INSERT INTO "foo" VALUES(2,'fjolnir','asgeirsson',1601);
COMMIT;