@{
    @"type": @"plural",
    @"pattern": @"$",
    @"replacement": @"s"
},

@{
    @"type": @"plural",
    @"pattern": @"s$",
    @"replacement": @"s"
},

@{
    @"type": @"plural",
    @"pattern": @"(ax|test)is$",
    @"replacement": @"$1es"
},

@{
    @"type": @"plural",
    @"pattern": @"(octop|vir)us$",
    @"replacement": @"$1i"
},

@{
    @"type": @"plural",
    @"pattern": @"(alias|status)$",
    @"replacement": @"$1es"
},

@{
    @"type": @"plural",
    @"pattern": @"(bu)s$",
    @"replacement": @"$1ses"
},

@{
    @"type": @"plural",
    @"pattern": @"(buffal|tomat)o$",
    @"replacement": @"$1oes"
},

@{
    @"type": @"plural",
    @"pattern": @"([ti])um$",
    @"replacement": @"$1a"
},

@{
    @"type": @"plural",
    @"pattern": @"sis$",
    @"replacement": @"ses
},

@{
    @"type": @"plural",
    @"pattern": @"(?:([^f])fe|([lr])f)$",
    @"replacement": @"$1$2ves"
},

@{
    @"type": @"plural",
    @"pattern": @"(hive)$",
    @"replacement": @"$1s"
},

@{
    @"type": @"plural",
    @"pattern": @"([^aeiouy]|qu)y$",
    @"replacement": @"$1ies"
},

@{
    @"type": @"plural",
    @"pattern": @"(x|ch|ss|sh)$",
    @"replacement": @"$1es"
},

@{
    @"type": @"plural",
    @"pattern": @"(matr|vert|ind)ix|ex$",
    @"replacement": @"$1ices"
},

@{
    @"type": @"plural",
    @"pattern": @"([m|l])ouse$",
    @"replacement": @"$1ice"
},

@{
    @"type": @"plural",
    @"pattern": @"^(ox)$",
    @"replacement": @"$1en"
},

@{
    @"type": @"plural",
    @"pattern": @"(quiz)$",
    @"replacement": @"$1zes"
},


@{
    @"type": @"singular",
    @"pattern": @"s$",
    @"replacement":"
},

@{
    @"type": @"singular",
    @"pattern": @"(n)ews$",
    @"replacement": @"$1ews"
},

@{
    @"type": @"singular",
    @"pattern": @"([ti])a$",
    @"replacement": @"$1um"
},

@{
    @"type": @"singular",
    @"pattern": @"((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$",
    @"replacement": @"$1\2sis"
},

@{
    @"type": @"singular",
    @"pattern": @"(^analy)ses$",
    @"replacement": @"$1sis"
},

@{
    @"type": @"singular",
    @"pattern": @"([^f])ves$",
    @"replacement": @"$1fe"
},

@{
    @"type": @"singular",
    @"pattern": @"(hive)s$",
    @"replacement": @"$1"
},

@{
    @"type": @"singular",
    @"pattern": @"(tive)s$",
    @"replacement": @"$1"
},

@{
    @"type": @"singular",
    @"pattern": @"([lr])ves$",
    @"replacement": @"$1f"
},

@{
    @"type": @"singular",
    @"pattern": @"([^aeiouy]|qu)ies$",
    @"replacement": @"$1y"
},

@{
    @"type": @"singular",
    @"pattern": @"(s)eries$",
    @"replacement": @"$1eries"
},

@{
    @"type": @"singular",
    @"pattern": @"(m)ovies$",
    @"replacement": @"$1ovie"
},

@{
    @"type": @"singular",
    @"pattern": @"(x|ch|ss|sh)es$",
    @"replacement": @"$1"
},

@{
    @"type": @"singular",
    @"pattern": @"([m|l])ice$",
    @"replacement": @"$1ouse"
},

@{
    @"type": @"singular",
    @"pattern": @"(bus)es$",
    @"replacement": @"$1"
},

@{
    @"type": @"singular",
    @"pattern": @"(o)es$",
    @"replacement": @"$1"
},

@{
    @"type": @"singular",
    @"pattern": @"(shoe)s$",
    @"replacement": @"$1"
},

@{
    @"type": @"singular",
    @"pattern": @"(cris|ax|test)es$",
    @"replacement": @"$1is"
},

@{
    @"type": @"singular",
    @"pattern": @"(octop|vir)i$",
    @"replacement": @"$1us"
},

@{
    @"type": @"singular",
    @"pattern": @"(alias|status)es$",
    @"replacement": @"$1"
},

@{
    @"type": @"singular",
    @"pattern": @"^(ox)en",
    @"replacement": @"$1"
},

@{
    @"type": @"singular",
    @"pattern": @"(vert|ind)ices$",
    @"replacement": @"$1ex"
},

@{
    @"type": @"singular",
    @"pattern": @"(matr)ices$",
    @"replacement": @"$1ix"
},

@{
    @"type": @"singular",
    @"pattern": @"(quiz)zes$",
    @"replacement": @"$1"
},

@{
    @"type": @"irregular",
    @"pattern": @"person",
    @"replacement": @"people"
},

@{
    @"type": @"irregular",
    @"pattern": @"man",
    @"replacement": @"men"
},

@{
    @"type": @"irregular",
    @"pattern": @"child",
    @"replacement": @"children"
},

@{
    @"type": @"irregular",
    @"pattern": @"sex",
    @"replacement": @"sexes"
},

@{
    @"type": @"irregular",
    @"pattern": @"move",
    @"replacement": @"moves"
},

@{
    @"type": @"uncountable",
    @"pattern": @"equipment"
},
@{
    @"type": @"uncountable",
    @"pattern": @"information"
},
@{
    @"type": @"uncountable",
    @"pattern": @"rice"
},
@{
    @"type": @"uncountable",
    @"pattern": @"money"
},
@{
    @"type": @"uncountable",
    @"pattern": @"species"
},
@{
    @"type": @"uncountable",
    @"pattern": @"series"
},
@{
    @"type": @"uncountable",
    @"pattern": @"fish"
},
@{
    @"type": @"uncountable",
    @"pattern": @"sheep"
}
