@{
    @"pattern": @"(quiz)zes$",
    @"replacement": @"$1"},
@{
    @"pattern": @"(matr)ices$",
    @"replacement": @"$1ix"},
@{
    @"pattern": @"(vert|ind)ices$",
    @"replacement": @"$1ex"},
@{
    @"pattern": @"^(ox)en",
    @"replacement": @"$1"},
@{
    @"pattern": @"(alias|status)es$",
    @"replacement": @"$1"},
@{
    @"pattern": @"(octop|vir)i$",
    @"replacement": @"$1us"},
@{
    @"pattern": @"(cris|ax|test)es$",
    @"replacement": @"$1is"},
@{
    @"pattern": @"(shoe)s$",
    @"replacement": @"$1"},
@{
    @"pattern": @"(o)es$",
    @"replacement": @"$1"},
@{
    @"pattern": @"(bus)es$",
    @"replacement": @"$1"},
@{
    @"pattern": @"([m|l])ice$",
    @"replacement": @"$1ouse"},
@{
    @"pattern": @"(x|ch|ss|sh)es$",
    @"replacement": @"$1"},
@{
    @"pattern": @"(m)ovies$",
    @"replacement": @"$1ovie"},
@{
    @"pattern": @"(s)eries$",
    @"replacement": @"$1eries"},
@{
    @"pattern": @"([^aeiouy]|qu)ies$",
    @"replacement": @"$1y"},
@{
    @"pattern": @"([lr])ves$",
    @"replacement": @"$1f"},
@{
    @"pattern": @"(tive)s$",
    @"replacement": @"$1"},
@{
    @"pattern": @"(hive)s$",
    @"replacement": @"$1"},
@{
    @"pattern": @"([^f])ves$",
    @"replacement": @"$1fe"},
@{
    @"pattern": @"(^analy)ses$",
    @"replacement": @"$1sis"},
@{
    @"pattern": @"((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$",
    @"replacement": @"$1\2sis"},
@{
    @"pattern": @"([ti])a$",
    @"replacement": @"$1um"},
@{
    @"pattern": @"(n)ews$",
    @"replacement": @"$1ews"},
@{
    @"pattern": @"s$",
    @"replacement": @""
}
