BEGIN TRANSACTION;
DROP TABLE IF EXISTS foo;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS belgians;
DROP TABLE IF EXISTS animals;
DROP TABLE IF EXISTS animals_people;
CREATE TABLE foo ("id" INTEGER PRIMARY KEY NOT NULL, "bar" varchar(255) DEFAULT NULL, "baz" TEXT DEFAULT NULL, "integer" integer DEFAULT NULL);
INSERT INTO "foo" VALUES(1,'foobarbaz','bazbazb',1337);
INSERT INTO "foo" VALUES(2,'fjolnir','asgeirsson',1601);
CREATE TABLE 'models'("id" INTEGER PRIMARY KEY NOT NULL, "name" varchar(255) DEFAULT NULL, "info" TEXT DEFAULT NULL);
INSERT INTO "models" VALUES(1,'a name','some info!');
INSERT INTO "models" VALUES(2,'another name','some more info!');
CREATE TABLE 'people'("id" INTEGER PRIMARY KEY NOT NULL, "userName" varchar(255) DEFAULT NULL, "realName" varchar(255) DEFAULT NULL, "modelId" INTEGER DEFAULT NULL);
INSERT INTO "people" VALUES(1,'aptiva','fjolnir asgeirsson',1);
INSERT INTO "people" VALUES(2,'god','steve wozniak',1);
INSERT INTO "people" VALUES(3,'co-god','steve jobs',0);
CREATE TABLE 'animals'("id" INTEGER PRIMARY KEY NOT NULL, "species" varchar(255) DEFAULT NULL, "nickname" varchar(255) DEFAULT NULL, "modelId");
INSERT INTO "animals" VALUES(1,'cat','awesome',1);
INSERT INTO "animals" VALUES(2,'dog','lame',1);
CREATE TABLE animals_people("animalId" INTEGER, "personId" INTEGER);
INSERT INTO "animals_people" VALUES(1,3);
CREATE TABLE 'belgians'("id" INTEGER PRIMARY KEY NOT NULL, "nickname" varchar(255) DEFAULT NULL,  "personId" INTEGER DEFAULT NULL);
INSERT INTO "belgians" VALUES(1,'denis',1);
INSERT INTO "belgians" VALUES(2,'chucker',1);
COMMIT;