BEGIN TRANSACTION;
DROP TABLE IF EXISTS foo;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS belgians;
DROP TABLE IF EXISTS animals;
DROP TABLE IF EXISTS animals_people;
CREATE TABLE foo ("identifier" VARCHAR(36) PRIMARY KEY NOT NULL, "bar" varchar(255) DEFAULT NULL, "baz" TEXT DEFAULT NULL, "integer" integer DEFAULT NULL);
INSERT INTO "foo" VALUES(1,'foobarbaz','bazbazb',1337);
INSERT INTO "foo" VALUES(2,'fjolnir','asgeirsson',1601);
CREATE TABLE 'models'("identifier" VARCHAR(36) PRIMARY KEY NOT NULL, "name" varchar(255) DEFAULT NULL, "info" TEXT DEFAULT NULL);
INSERT INTO "models" VALUES(1,'a name','some info!');
INSERT INTO "models" VALUES(2,'another name','some more info!');
CREATE TABLE 'people'("identifier" VARCHAR(36) PRIMARY KEY NOT NULL, "userName" varchar(255) DEFAULT NULL, "realName" varchar(255) DEFAULT NULL, "modelIdentifier" VARCHAR(36) DEFAULT NULL);
INSERT INTO "people" VALUES(1,'aptiva','fjolnir asgeirsson',1);
INSERT INTO "people" VALUES(2,'god','steve wozniak',1);
INSERT INTO "people" VALUES(3,'co-god','steve jobs',0);
CREATE TABLE 'animals'("identifier" VARCHAR(36) PRIMARY KEY NOT NULL, "species" varchar(255) DEFAULT NULL, "nickname" varchar(255) DEFAULT NULL, "modelIdentifier" VARCHAR(36));
INSERT INTO "animals" VALUES(1,'cat','awesome',1);
INSERT INTO "animals" VALUES(2,'dog','lame',1);
CREATE TABLE animals_people("animalIdentifier" VARCHAR(36), "personIdentifier" VARCHAR(36));
INSERT INTO "animals_people" VALUES(1,3);
CREATE TABLE 'belgians'("identifier" VARCHAR(36) PRIMARY KEY NOT NULL, "nickname" varchar(255) DEFAULT NULL,  "personIdentifier" VARCHAR(36) DEFAULT NULL);
INSERT INTO "belgians" VALUES(1,'denis',1);
INSERT INTO "belgians" VALUES(2,'chucker',1);
COMMIT;